name: Build and Test Docker Image

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build local Docker image
        run: docker build -t flask-app:latest .

      - name: Start flask app container
        run: docker run -d -p 5000:5000 --name flask-app flask-app:latest

      - name: Time for API to boot
        run: sleep 2

      - name: Test /health endpoint
        run: |
          echo "Testing API Health check..."
          curl --fail http://localhost:5000/health

      - name: Show container logs
        if: always()
        run: docker logs flask-app