name: Build and Test Docker Image

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    
jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout repository code
              uses: actions/checkout@v4


            - name: List files in repository
              run: ls -la

            - name: Build Docker Image
              run: docker build -t test-app:latest .

            - name: Run container tests
              run: docker run --rm test-app:latest

